#!/bin/bash

if [ -z "$BASE_DIR" ]; then
  DIR=$(dirname "$(realpath $0)")
  BASE_DIR=$(dirname $DIR)

  source $DIR/load-env.sh
fi

bosh int $BASE_DIR/$BOSH_ALIAS/bosh-vars.yml --path /jumpbox_ssh/private_key > $BASE_DIR/$BOSH_ALIAS/jumpbox.key
chmod 600 $BASE_DIR/$BOSH_ALIAS/jumpbox.key

set +e
ssh-keygen -R $BOSH_IP
set -e

OUTPUT=$(ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no jumpbox@$BOSH_IP \
  -i $BASE_DIR/$BOSH_ALIAS/jumpbox.key "cat /var/vcap/jobs/vsphere_cpi/config/cpi.json")

echo "$OUTPUT" | jq '.cloud.properties.vcenters[] | .datacenters[] | .datastore_pattern'
echo "$OUTPUT" | jq '.cloud.properties.vcenters[] | .datacenters[] | .persistent_datastore_pattern'
