#!/bin/bash -e

if [ -z "$__BASEDIR__" ]; then
  FILE_PATH=$(cd -P -- "$(dirname -- "$0")" && printf '%s\n' "$(pwd -P)/$(basename -- "$0")")
  __DIR__="$( cd "$( dirname "${FILE_PATH}" )" && pwd )"
  __BASEDIR__=$(dirname $__DIR__)

  source $__DIR__/load-env.sh
fi

export BOSH_ENVIRONMENT=$BOSH_IP
export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=$($BOSH_CMD int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /admin_password)
export BOSH_CA_CERT="$($BOSH_CMD int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /director_ssl/ca)"

unsetDnsOnWifiAdapter
