#!/bin/bash -e

if [ -z "$__BASEDIR__" ]; then
  __DIR__=$(dirname "$(realpath $0)")
  __BASE_DIR__=$(dirname $__DIR__)

  source $__DIR__/load-env.sh
fi

bosh int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /jumpbox_ssh/private_key > $__BASEDIR__/$BOSH_ALIAS/jumpbox.key
chmod 600 $__BASEDIR__/$BOSH_ALIAS/jumpbox.key

set +e
ssh-keygen -R $BOSH_IP
set -e

ssh jumpbox@$BOSH_IP -i $__BASEDIR__/$BOSH_ALIAS/jumpbox.key
