#!/bin/bash

if [ -z "$__BASEDIR__" ]; then
  __DIR__=$(dirname "$(realpath $0)")
  __BASEDIR__=$(dirname $__DIR__)

  source $__DIR__/load-env.sh
fi

export BOSH_ENVIRONMENT=$BOSH_IP
export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=$(bosh int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /admin_password)
export BOSH_CA_CERT="$(bosh int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /director_ssl/ca)"

unsetDnsOnWifiAdapter
