#!/bin/bash

if [ -z "$__BASEDIR__" ]; then
  FILE_PATH=$(cd -P -- "$(dirname -- "$0")" && printf '%s\n' "$(pwd -P)/$(basename -- "$0")")
  __DIR__="$( cd "$( dirname "${FILE_PATH}" )" && pwd )"
  __BASEDIR__=$(dirname $__DIR__)

  source $__DIR__/load-env.sh
fi

bosh int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /jumpbox_ssh/private_key > $__BASEDIR__/$BOSH_ALIAS/jumpbox.key
chmod 600 $__BASEDIR__/$BOSH_ALIAS/jumpbox.key

set +e
ssh-keygen -R $BOSH_IP
set -e

OUTPUT=$(ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no jumpbox@$BOSH_IP \
  -i $__BASEDIR__/$BOSH_ALIAS/jumpbox.key "cat /var/vcap/jobs/vsphere_cpi/config/cpi.json")

echo "$OUTPUT" | jq '.cloud.properties.vcenters[] | .datacenters[] | .datastore_pattern'
echo "$OUTPUT" | jq '.cloud.properties.vcenters[] | .datacenters[] | .persistent_datastore_pattern'
