#!/bin/bash

if [ -z "$__BASEDIR__" ]; then
  __DIR__=$(dirname "$(realpath $0)")
  __BASEDIR__=$(dirname $__DIR__)

  source $__DIR__/load-env.sh
fi

bosh int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /jumpbox_ssh/private_key > $__BASEDIR__/$BOSH_ALIAS/jumpbox.key
chmod 600 $__BASEDIR__/$BOSH_ALIAS/jumpbox.key

set +e
ssh-keygen -R $BOSH_IP
set -e

OUTPUT=$(ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no jumpbox@$BOSH_IP \
  -i $__BASEDIR__/$BOSH_ALIAS/jumpbox.key "/var/vcap/packages/postgres-10/bin/psql -qtAX -U vcap bosh -h 127.0.0.1 -c \"select value from director_attributes where name = 'resurrection_paused'\"")

echo "{"resurrection_paused": "$OUTPUT"}"
