#!/bin/bash -e

if [ -z "$BASE_DIR" ]; then
  DIR=$(dirname "$(realpath $0)")
  BASE_DIR=$(dirname $DIR)

  source $DIR/load-env.sh
fi

bosh int $BASE_DIR/$BOSH_ALIAS/bosh-vars.yml --path /jumpbox_ssh/private_key > $BASE_DIR/$BOSH_ALIAS/jumpbox.key
chmod 600 $BASE_DIR/$BOSH_ALIAS/jumpbox.key

set +e
ssh-keygen -R $BOSH_IP
set -e

ssh jumpbox@$BOSH_IP -i $BASE_DIR/$BOSH_ALIAS/jumpbox.key
