#!/bin/bash

__DIR__=$(dirname "$(realpath $0)")
__BASEDIR__=$(dirname $__DIR__)

source $__DIR__/load-env.sh

export CREDHUB_CLIENT=director_to_credhub
export CREDHUB_SECRET=$(bosh int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /uaa_clients_director_to_credhub)
export CREDHUB_SERVER=https://$BOSH_IP:8844
export CREDHUB_CA_CERT=$(bosh int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /credhub_tls/ca)
export CREDHUB_CA_CERT="$CREDHUB_CA_CERT"\\n$(bosh int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /uaa_ssl/ca)

credhub api

echo "Connected to director credhub..."

