#!/bin/bash

if [ -z "$BASE_DIR" ]; then
  DIR=$(dirname "$(realpath $0)")
  BASE_DIR=$(dirname $DIR)

  source $DIR/load-env.sh
fi

export BOSH_ENVIRONMENT=$BOSH_IP
export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=$(bosh int $BASE_DIR/$BOSH_ALIAS/bosh-vars.yml --path /admin_password)
export BOSH_CA_CERT="$(bosh int $BASE_DIR/$BOSH_ALIAS/bosh-vars.yml --path /director_ssl/ca)"

unsetDnsOnWifiAdapter
