#!/bin/bash

if [ -z "$__BASE_DIR__" ]; then
  __DIR__=$(dirname "$(realpath $0)")
  __BASE_DIR__=$(dirname $__DIR__)

  source $__DIR__/load-env.sh
fi

export CREDHUB_CLIENT=director_to_credhub
export CREDHUB_SECRET=$(bosh int $__BASE_DIR__/$BOSH_ALIAS/bosh-vars.yml --path /uaa_clients_director_to_credhub)
export CREDHUB_SERVER=https://$BOSH_IP:8844
export CREDHUB_CA_CERT=$(bosh int $__BASE_DIR__/$BOSH_ALIAS/bosh-vars.yml --path /credhub_tls/ca)
export CREDHUB_CA_CERT="$CREDHUB_CA_CERT"\\n$(bosh int $__BASE_DIR__/$BOSH_ALIAS/bosh-vars.yml --path /uaa_ssl/ca)

echo "Connected to director credhub..."

CONCOURSE_UAA_ADMIN=$(credhub get -n /concourse-bosh/concourse/uaa_admin -j | jq -r '.value')
CONCOURSE_UAA_ADMIN_SECRET=$(credhub get -n /concourse-bosh/concourse/uaa_admin -j | jq -r '.value')
