#!/bin/bash

__DIR__=$(dirname "$(realpath $0)")
__BASEDIR__=$(dirname $__DIR__)

source $__DIR__/load-env.sh

export CREDHUB_CLIENT=director_to_credhub
export CREDHUB_SECRET=$(bosh int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /uaa_clients_director_to_credhub)
export CREDHUB_SERVER=https://$BOSH_IP:8844
export CREDHUB_CA_CERT=$(bosh int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /credhub_tls/ca)
export CREDHUB_CA_CERT="$CREDHUB_CA_CERT"\\n$(bosh int $__BASEDIR__/$BOSH_ALIAS/bosh-vars.yml --path /uaa_ssl/ca)

credhub login

echo "Connected to director credhub..."

CREDHUB_CONCOURSE_CA=$(credhub get -n /$BOSH_ALIAS/concourse/atc_tls -j | jq -r '.value.certificate')
CREDHUB_CONCOURSE_SECRET=$(credhub get -n /$BOSH_ALIAS/concourse/concourse_to_credhub_client_secret -j | jq -r '.value')

export CREDHUB_CLIENT=concourse_to_credhub_client
export CREDHUB_SECRET=$CREDHUB_CONCOURSE_SECRET
export CREDHUB_SERVER=$CONCOURSE_EXTERNAL_URL:8844
export CREDHUB_CA_CERT=$CREDHUB_CONCOURSE_CA

credhub login

echo "Connected to concourse credhub..."
