#!/bin/bash -e

if [ -z "$__BASE_DIR__" ]; then
  __DIR__=$(dirname "$(realpath $0)")
  __BASE_DIR__=$(dirname $__DIR__)

  source $__DIR__/load-env.sh
fi

function createBoshDeploymentVarsFile() {
  cp $__BASE_DIR__/misc/bosh-vars-template.yml $__BASE_DIR__/$BOSH_VAR_FILE

  yq eval ".director_name=\"$BOSH_ALIAS\"" $__BASE_DIR__/$BOSH_VAR_FILE 
  yq eval ".internal_cidr=\"$NETWORK_CIDR\"" $__BASE_DIR__/$BOSH_VAR_FILE 
  yq eval ".internal_gw=\"$NETWORK_GATEWAY\"" $__BASE_DIR__/$BOSH_VAR_FILE 
  yq eval ".internal_ip=\"$BOSH_IP\"" $__BASE_DIR__/$BOSH_VAR_FILE 
  yq eval ".internal_dns=$DNS_SERVERS" $__BASE_DIR__/$BOSH_VAR_FILE 
  yq eval ".network_name=\"$VCENTER_NETWORK_NAME\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vcenter_dc=\"$VSPHERE_DATACENTER\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vcenter_ds=\"$VCENTER_STORAGE_NAME\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vcenter_ip=\"$VCENTER_IP\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vcenter_user=\"$VCENTER_USERNAME\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vcenter_password=\"$VCENTER_PASSWORD\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vcenter_templates=\"$VCENTER_VM_TEMPLATES_FOLDER_NAME\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vcenter_vms=\"$VCENTER_VMS_FOLDER_NAME\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vcenter_disks=\"$VCENTER_DISK_FOLDER_NAME\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vcenter_cluster=\"$VCENTER_CLUSTER_NAME\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vcenter_rp=\"$VCENTER_RESOURCE_POOL\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".bosh_release_url=\"$BOSH_RELEASE_URL\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".bosh_release_sha=\"$BOSH_RELEASE_SHA\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vsphere_cpi_release_url=\"$VSPHERE_CPI_URL\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".vsphere_cpi_release_sha=\"$VSPHERE_CPI_SHA\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".stemcell_url=\"$STEMCELL_URL\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".stemcell_sha=\"$STEMCELL_SHA\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".os_conf_release_url=\"$OS_CONF_RELEASE_URL\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".os_conf_release_sha=\"$OS_CONF_RELEASE_SHA\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".uaa_release_url=\"$UAA_RELEASE_URL\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".uaa_release_sha=\"$UAA_RELEASE_SHA\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".credhub_release_url=\"$BOSH_CREDHUB_RELEASE_URL\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".credhub_release_sha=\"$BOSH_CREDHUB_RELEASE_SHA\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".syslog_address=\"$SYSLOG_ADDRESS\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".syslog_port=\"$SYSLOG_PORT\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".syslog_transport=\"$SYSLOG_TRANSPORT\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".tsdb_address=\"$TSDB_ADDRESS\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".tsdb_port=\"$TSDB_PORT\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".nsxt_host=\"$NSX_HOST\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".nsxt_user=\"$NSX_USERNAME\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".nsxt_password=\"$NSX_PASSWORD\"" $__BASE_DIR__/$BOSH_VAR_FILE
  yq eval ".nsxt_ca_cert=\"$(< /tmp/nsx.pem)\"" $__BASE_DIR__/$BOSH_VAR_FILE
}

function createConcourseDeploymentVarsFile() {
  cp $__BASE_DIR__/misc/concourse-vars-template.yml $__BASE_DIR__/$CONCOURSE_VAR_FILE

  yq eval ".linux_release=\"$LINUX_RELEASE\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".local_user.username=\"$CONCOURSE_ADMIN_USERNAME\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".local_user.password=\"$CONCOURSE_ADMIN_PASSWORD\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".deployment_name=\"concourse\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".az_name=\"$CONCOURSE_AZ_NAME\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".network_name=\"$CONCOURSE_NW_NAME\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".web_network_name=\"$CONCOURSE_NW_NAME\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".web_static_ips=\"$CONCOURSE_WEB_STATIC_IPS\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".concourse_db_ip=\"$CONCOURSE_DB_STATIC_IPS\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".worker_static_ips=\"$CONCOURSE_WORKER_STATIC_IPS\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".external_host=\"$CONCOURSE_FQDN\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".external_url=\"$CONCOURSE_EXTERNAL_URL\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".web_instances=\"$ATC_WEB_INSTANCES\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".web_vm_type=\"$ATC_WEB_VM_TYPE\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".db_instances=\"$CONCOURSE_DB_INSTANCES\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".db_vm_type=\"$CONCOURSE_DB_VM_TYPE\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".db_persistent_disk_type=\"$CONCOURSE_DB_PERSISTENT_DISK_TYPE\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".worker_instances=\"$CONCOURSE_WORKER_INSTANCES\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".worker_vm_type=\"$CONCOURSE_WORKER_VM_TYPE\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".github_client.username=\"$GIT_CLIENT_USERNAME\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".github_client.password=\"$GIT_CLIENT_TOKEN\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".main_team.github_users=\"$GIT_USERS\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".main_team.github_orgs=\"$GIT_ORGS\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".main_team.github_teams=\"$GIT_TEAMS\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".bbr_sdk_version=\"$BBR_RELEASE_VERSION\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".bbr_sdk_sha1=\"$BBR_RELEASE_SHA\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".uaa_version=\"$UAA_RELEASE_VERSION\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".uaa_sha1=\"$UAA_RELEASE_SHA\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".credhub_version=\"$CREDHUB_RELEASE_VERSION\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".credhub_sha1=\"$CREDHUB_RELEASE_SHA\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".volume_sweeper_max_in_flight=\"$VOLUME_SWEEPER_MAX_IN_FLIGHT\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".worker_rebalance_interval=\"$WORKER_REBALANCE_INTERVAL\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".worker_update_max_in_flight=\"$WORKER_UPDATE_MAX_IN_FLIGHT\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
  yq eval ".credhub_path_prefix=\"$CONCOURSE_PATH_PREFIX\"" $__BASE_DIR__/$CONCOURSE_VAR_FILE
}

function createCloudConfigVarsFile() {
  cp $__BASE_DIR__/misc/cloud-config-vars-template.yml $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
  yq eval ".dns_servers=$DNS_SERVERS" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
  yq eval ".reserved_ips=$RESERVED_IPS" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE 
  yq eval "static_ips=$CLOUD_CONFIG_STATIC_IPS" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
  yq eval ".az_name=\"$CONCOURSE_AZ_NAME\"" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
  yq eval ".nw_name=\"$CONCOURSE_NW_NAME\"" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
  yq eval ".vcenter_cluster=\"$VCENTER_CLUSTER_NAME\"" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
  yq eval ".network_cidr=\"$NETWORK_CIDR\"" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
  yq eval ".network_name=\"$VCENTER_NETWORK_NAME\"" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
  yq eval ".network_gateway=\"$NETWORK_GATEWAY\"" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
  yq eval ".vcenter_rp=\"$VCENTER_RESOURCE_POOL\"" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
  yq eval ".vm_disk_type=\"$VM_DISK_TYPE\"" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
  yq eval ".compilation_vm_type=\"$COMPILATION_VM_TYPE\"" $__BASE_DIR__/$CLOUD_CONFIG_VAR_FILE
}
