#!/bin/bash

if [ -z "$BASE_DIR" ]; then
  DIR=$(dirname "$(realpath $0)")
  BASE_DIR=$(dirname $DIR)

  source $DIR/load-env.sh
fi

export VAULT_TOKEN=$(cat $BASE_DIR/$BOSH_ALIAS/vault.log | grep 'Initial Root Token' | awk '{print $4}')
vault login $VAULT_TOKEN
