#!/bin/bash

if [ -z "$__BASEDIR__" ]; then
  __DIR__=$(dirname "$(realpath $0)")
  __BASEDIR__=$(dirname $__DIR__)

  source $__DIR__/load-env.sh
fi

export VAULT_TOKEN=$(cat $__BASEDIR__/$BOSH_ALIAS/vault.log | grep 'Initial Root Token' | awk '{print $4}')
vault login $VAULT_TOKEN
