#!/bin/bash

if [ -z "$__BASE_DIR__" ]; then
  __DIR__=$(dirname "$(realpath $0)")
  __BASE_DIR__=$(dirname $__DIR__)

  source $DIR/load-env.sh
fi

export VAULT_TOKEN=$(cat $__BASE_DIR__/$BOSH_ALIAS/vault.log | grep 'Initial Root Token' | awk '{print $4}')
vault login $VAULT_TOKEN
