#!/bin/bash

if [ -z "$__BASEDIR__" ]; then
  __DIR__=$(dirname "$(realpath $0)")
  __BASEDIR__=$(dirname $__DIR__)

  source $__DIR__/load-env.sh
fi

export VAULT_ADDR=$1

set +x
export VAULT_TOKEN=$(cat $__BASEDIR__/$BOSH_ALIAS/vault.log | grep 'Initial Root Token' | awk '{print $4}')

vault operator unseal $(cat $__BASEDIR__/$BOSH_ALIAS/vault.log | grep 'Unseal Key 1' | awk '{print $4}')
vault operator unseal $(cat $__BASEDIR__/$BOSH_ALIAS/vault.log | grep 'Unseal Key 2' | awk '{print $4}')
vault operator unseal $(cat $__BASEDIR__/$BOSH_ALIAS/vault.log | grep 'Unseal Key 3' | awk '{print $4}')
set -x
