#!/bin/bash

if [ -z "$BASE_DIR" ]; then
  DIR=$(dirname "$(realpath $0)")
  BASE_DIR=$(dirname $DIR)

  source $DIR/load-env.sh
fi

export VAULT_ADDR=$1

set +x
export VAULT_TOKEN=$(cat $BASE_DIR/$BOSH_ALIAS/vault.log | grep 'Initial Root Token' | awk '{print $4}')

vault operator unseal $(cat $BASE_DIR/$BOSH_ALIAS/vault.log | grep 'Unseal Key 1' | awk '{print $4}')
vault operator unseal $(cat $BASE_DIR/$BOSH_ALIAS/vault.log | grep 'Unseal Key 2' | awk '{print $4}')
vault operator unseal $(cat $BASE_DIR/$BOSH_ALIAS/vault.log | grep 'Unseal Key 3' | awk '{print $4}')
set -x
